[2023-02-09T08:42:52.874+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T08:42:52.277011+00:00 [queued]>
[2023-02-09T08:42:52.886+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T08:42:52.277011+00:00 [queued]>
[2023-02-09T08:42:52.886+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:42:52.886+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-02-09T08:42:52.886+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:42:52.901+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): bash_command> on 2023-02-09 08:42:52.277011+00:00
[2023-02-09T08:42:52.906+0000] {standard_task_runner.py:55} INFO - Started process 6619 to run task
[2023-02-09T08:42:52.909+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawler-dag1', 'bash_command', 'manual__2023-02-09T08:42:52.277011+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/crawler-dag.py', '--cfg-path', '/tmp/tmpw_6rhk4o']
[2023-02-09T08:42:52.909+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask bash_command
[2023-02-09T08:42:52.957+0000] {task_command.py:389} INFO - Running <TaskInstance: crawler-dag1.bash_command manual__2023-02-09T08:42:52.277011+00:00 [running]> on host 3d45bdeeaf4a
[2023-02-09T08:42:53.017+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crawler-dag1
AIRFLOW_CTX_TASK_ID=bash_command
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T08:42:52.277011+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T08:42:52.277011+00:00
[2023-02-09T08:42:53.017+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-09T08:42:53.018+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/crawler/dmx.py']
[2023-02-09T08:42:53.028+0000] {subprocess.py:86} INFO - Output:
[2023-02-09T08:42:53.541+0000] {subprocess.py:93} INFO - /opt/***/crawler/dmx.py:25: DeprecationWarning: use options instead of chrome_options
[2023-02-09T08:42:53.541+0000] {subprocess.py:93} INFO -   browser = webdriver.Chrome(executable_path="chromedriver", chrome_options=chrome_options)
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO -   File "/opt/***/crawler/dmx.py", line 25, in <module>
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO -     browser = webdriver.Chrome(executable_path="chromedriver", chrome_options=chrome_options)
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO -     keep_alive,
[2023-02-09T08:42:53.542+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO -     self.service.start()
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO -     self.assert_process_still_running()
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO -     return_code = self.process.poll()
[2023-02-09T08:42:53.543+0000] {subprocess.py:93} INFO - AttributeError: 'Service' object has no attribute 'process'
[2023-02-09T08:42:53.570+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-09T08:42:53.580+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-09T08:42:53.585+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=crawler-dag1, task_id=bash_command, execution_date=20230209T084252, start_date=20230209T084252, end_date=20230209T084253
[2023-02-09T08:42:53.596+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task bash_command (Bash command failed. The command returned a non-zero exit code 1.; 6619)
[2023-02-09T08:42:53.641+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-09T08:42:53.659+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
