[2023-02-09T08:23:05.949+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag.bash_command manual__2023-02-09T08:23:04.920325+00:00 [queued]>
[2023-02-09T08:23:05.957+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag.bash_command manual__2023-02-09T08:23:04.920325+00:00 [queued]>
[2023-02-09T08:23:05.957+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:23:05.957+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-02-09T08:23:05.957+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:23:05.969+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): bash_command> on 2023-02-09 08:23:04.920325+00:00
[2023-02-09T08:23:05.974+0000] {standard_task_runner.py:55} INFO - Started process 4321 to run task
[2023-02-09T08:23:05.976+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawler-dag', 'bash_command', 'manual__2023-02-09T08:23:04.920325+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/crawler-dag.py', '--cfg-path', '/tmp/tmpnt21ex9q']
[2023-02-09T08:23:05.977+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask bash_command
[2023-02-09T08:23:06.021+0000] {task_command.py:389} INFO - Running <TaskInstance: crawler-dag.bash_command manual__2023-02-09T08:23:04.920325+00:00 [running]> on host 9fd6eb33fd9d
[2023-02-09T08:23:06.079+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crawler-dag
AIRFLOW_CTX_TASK_ID=bash_command
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T08:23:04.920325+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T08:23:04.920325+00:00
[2023-02-09T08:23:06.080+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-09T08:23:06.081+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/crawler/dmx.py']
[2023-02-09T08:23:06.091+0000] {subprocess.py:86} INFO - Output:
[2023-02-09T08:23:06.618+0000] {subprocess.py:93} INFO - /opt/***/crawler/dmx.py:25: DeprecationWarning: use options instead of chrome_options
[2023-02-09T08:23:06.618+0000] {subprocess.py:93} INFO -   browser = webdriver.Chrome(executable_path="chromedriver", chrome_options=chrome_options)
[2023-02-09T08:23:06.618+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-09T08:23:06.618+0000] {subprocess.py:93} INFO -   File "/opt/***/crawler/dmx.py", line 25, in <module>
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -     browser = webdriver.Chrome(executable_path="chromedriver", chrome_options=chrome_options)
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 89, in __init__
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -     keep_alive,
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -     self.service.start()
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -     self.assert_process_still_running()
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO -     return_code = self.process.poll()
[2023-02-09T08:23:06.619+0000] {subprocess.py:93} INFO - AttributeError: 'Service' object has no attribute 'process'
[2023-02-09T08:23:06.653+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-09T08:23:06.665+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-09T08:23:06.670+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=crawler-dag, task_id=bash_command, execution_date=20230209T082304, start_date=20230209T082305, end_date=20230209T082306
[2023-02-09T08:23:06.685+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task bash_command (Bash command failed. The command returned a non-zero exit code 1.; 4321)
[2023-02-09T08:23:06.709+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-09T08:23:06.729+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
